import { marksoffreedomGunma2026ImageList } from "@/app/api/images/marksoffreedom-gunma-2026/data";
import { marksoffreedomIshikawa2025ImageList } from "@/app/api/images/marksoffreedom-ishikawa-2025/data";
import { marksoffreedomSapporo2025ImageList } from "@/app/api/images/marksoffreedom-sapporo-2025/data";
import { marksoffreedomTokyo2025ImageList } from "@/app/api/images/marksoffreedom-tokyo-2025/data";
import { marksoffreedomTokyo2026ImageList } from "@/app/api/images/marksoffreedom-tokyo-2026/data";

export type MofCaption = {
  ja?: string;
  en?: string;
};

export type MofPhoto = {
  file: string;
  /** Default: true */
  visible?: boolean;
  caption?: MofCaption;
};

export type MofSeriesSection = "featured" | "archive";

export type MofSeries = {
  id: string;
  title: string;
  year: string;
  /** Default: true — set false to hide the entire series */
  visible?: boolean;
  section: MofSeriesSection;
  imageDir: string;
  photos: MofPhoto[];
};

/** Per-file overrides: visibility and captions without re-listing every filename. */
type PhotoOverrides = Record<string, { visible?: boolean; caption?: MofCaption }>;

function photosFromFiles(
  files: string[],
  overrides: PhotoOverrides = {},
): MofPhoto[] {
  return files.map((file) => ({
    file,
    ...overrides[file],
  }));
}

/**
 * Marks of Freedom series registry.
 *
 * - Series: set `visible: false` to hide a whole series.
 * - Photos: set `visible: false` in overrides, or on individual entries.
 * - Captions: add `caption: { ja: "...", en: "..." }` in overrides or per photo.
 */
export const mofSeries: MofSeries[] = [
  {
    id: "tokyo-2026",
    title: "Marks of Freedom — Tokyo 2026",
    year: "2026",
    visible: true,
    section: "featured",
    imageDir: "/images/marksoffreedom/tokyo-2026",
    photos: photosFromFiles(marksoffreedomTokyo2026ImageList, {
      // Example:
      // "tokyo03.png": { visible: false },
      // "tokyo05.png": { caption: { ja: "...", en: "..." } },
    }),
  },
  {
    id: "gunma-2026",
    title: "Marks of Freedom — Gunma 2026",
    year: "2026",
    visible: true,
    section: "archive",
    imageDir: "/images/marksoffreedom/gunma-2026",
    photos: photosFromFiles(marksoffreedomGunma2026ImageList),
  },
  {
    id: "tokyo-2025",
    title: "Marks of Freedom — Tokyo 2025",
    year: "2025",
    visible: true,
    section: "archive",
    imageDir: "/images/marksoffreedom/tokyo-2025",
    photos: photosFromFiles(marksoffreedomTokyo2025ImageList),
  },
  {
    id: "ishikawa-2025",
    title: "Marks of Freedom — Kanazawa 2025",
    year: "2025",
    visible: true,
    section: "archive",
    imageDir: "/images/marksoffreedom/ishikawa-2025",
    photos: photosFromFiles(marksoffreedomIshikawa2025ImageList),
  },
  {
    id: "sapporo-2025",
    title: "Marks of Freedom — Sapporo 2025",
    year: "2025",
    visible: true,
    section: "archive",
    imageDir: "/images/marksoffreedom/sapporo-2025",
    photos: photosFromFiles(marksoffreedomSapporo2025ImageList),
  },
];

export function getPhotoSrc(series: MofSeries, photo: MofPhoto): string {
  return `${series.imageDir}/${photo.file}`;
}

/** WebP thumbnails live in `{imageDir}/thumbs/` — generated by generateMofThumbnails. */
export function getPhotoThumbSrc(series: MofSeries, photo: MofPhoto): string {
  const base = photo.file.replace(/\.[^.]+$/, "");
  return `${series.imageDir}/thumbs/${base}.webp`;
}

export function getVisiblePhotos(series: MofSeries): MofPhoto[] {
  if (series.visible === false) return [];
  return series.photos.filter((photo) => photo.visible !== false);
}

export function getVisibleSeries(section?: MofSeriesSection): MofSeries[] {
  return mofSeries.filter(
    (series) =>
      series.visible !== false &&
      (section === undefined || series.section === section),
  );
}
